name: Report issues with software on freeCodeCamp.org's platforms
description: Report a software bug on `/learn`, `/news`, Community Forum, Code Radio, or any of the platforms.
title: ''
labels: ['type: bug', 'status: waiting triage']
assignees: ''
body:
  - type: markdown
    attributes:
      value: If you're reporting a security issue, don't create a GitHub issue. Instead, visit https://contribute.freecodecamp.org/#/security.
  - type: input
    attributes:
      label: Affected Page
      description: Add a link to the coding challenge with the problem.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to Reproduce
      description: Please provide the steps to reproduce the issue.
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected behavior
      description: Add a clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem. You can drag and drop `png`, `jpg`, `gif`, etc. in this box.
    validations:
      required: false
  - type: textarea
    attributes:
      label: System
      description: Please complete the following information.
      placeholder: |
        - Device: [e.g. iPhone 6, Laptop]
        - OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
        - Browser: [e.g. Chrome, Safari]
        - Version: [e.g. 22]
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
    validations:
      required: false
