name: Crowdin Curriculum Download
on:
  workflow_dispatch:

jobs:
  i18n-download-curriculum-translations:
    name: Learn
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout Source Files
        uses: actions/checkout@v2

      - name: Install Dependencies
        working-directory: ./tools
        run: |
          cd ./crowdin
          npm ci

      ##### Download Chinese #####
      - name: Crowdin Download Chinese Translations
        uses: crowdin/github-action@master
        # options: https://github.com/crowdin/github-action/blob/master/action.yml
        with:
          # uploads
          upload_sources: false
          upload_translations: false
          auto_approve_imported: false
          import_eq_suggestions: false

          # downloads
          download_translations: true
          download_language: zh-CN
          skip_untranslated_files: true
          export_only_approved: true

          push_translations: false

          # pull-request
          create_pull_request: false

          # global options
          config: './config/crowdin/curriculum/crowdin.yml'
          base_url: ${{ secrets.CROWDIN_BASE_URL_FCC }}

          # Uncomment below to debug
          # dryrun_action: true

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID_CURRICULUM }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_CAMPERBOT_SERVICE_TOKEN }}

      # Convert Simplified Chinese to Traditional #
      - name: Generate Translations
        uses: ./tools/crowdin/actions/convert-chinese
 
      ##### Download Espanol #####
      - name: Crowdin Download Espanol Translations
        uses: crowdin/github-action@master
        # options: https://github.com/crowdin/github-action/blob/master/action.yml
        with:
          # uploads
          upload_sources: false
          upload_translations: false
          auto_approve_imported: false
          import_eq_suggestions: false

          # downloads
          download_translations: true
          download_language: es-EM
          skip_untranslated_files: true
          export_only_approved: true

          push_translations: false

          # pull-request
          create_pull_request: false

          # global options
          config: './config/crowdin/curriculum/crowdin.yml'
          base_url: ${{ secrets.CROWDIN_BASE_URL_FCC }}

          # Uncomment below to debug
          # dryrun_action: true

        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_CAMPERBOT_PA_TOKEN }}
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID_CURRICULUM }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_CAMPERBOT_SERVICE_TOKEN }}

      # Create Commit
      - name: Commit Changes
        env:
          EMAIL: ${{ secrets.ACTIONS_CAMPERBOT_EMAIL }}
        run: |
          git checkout -b i18n-sync-curriculum
          git config --global user.name "nhtest"
          git config --global user.email "nhcarrigan+test@gmail.com"
          git add .
          git commit -m "chore: update translations"
          git push -u origin i18n-sync-curriculum -f

      # Generate PR #
      # Alll languages should go ABOVE this. #

      - name: Create PR
        uses: ./tools/crowdin/actions/pr-creator
        with:
          github-token: ${{ secrets.ACTIONS_CAMPERBOT_PA_TOKEN }}
          branch: 'i18n-sync-curriculum'
          owner-repo: 'nhcarrigan/actions-testing'
          base: 'main'
          title: 'chore(i18n,learn): processed translations'
          body: 'This PR was opened auto-magically by Crowdin.'
          labels: 'crowdin-sync, scope: i18n, scope: learn'
          reviewers: 'nhcarrigan'
