name: Crowdin Curriculum Download
on:
  workflow_dispatch:
  schedule:
    - cron: "0 12 * * *"

jobs:
  i18n-download-curriculum-translations:
    name: Learn
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout Source Files
        uses: actions/checkout@v2



      # Generate PR - all languages should go ABOVE this. #

      - name: Create PR
        id: cpr
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.ACTIONS_CAMPERBOT_PA_TOKEN }}
          script: |
            const PR = await github.pulls.create({
              owner: 'nhcarrigan',
              repo: 'actions-testing',
              head: 'i18n-sync-learn',
              base: 'main',
              title: 'Crowdin Sync Learn',
              body: 'This PR was opened automagically by Crowdin.'
            });
            const PRNumber = PR.data.number;
            await github.issues.addLabels({
              owner: 'nhcarrigan',
              repo: 'actions-testing',
              issue_number: PRNumber,
              labels: [
                "crowdin-sync",
                "scope: i18n",
                "scope: learn"
              ]
            })