name: Crowdin Curriculum Download
on:
  workflow_dispatch:

jobs:
  i18n-download-curriculum-translations:
    name: Learn
    runs-on: ubuntu-18.04
    steps:
      # Generate PR - all languages should go ABOVE this. #
      - name: Install Dependencies
        working-directory: ./tools
        run: |
          pwd
          ls
          cd ./crowdin
          npm ci
          
      # Generate PR - all languages should go ABOVE this. #
      - name: Create PR
        uses: ./tools/crowdin/actions/pr-creator
        with:
          github-token: ${{ secrets.ACTIONS_CAMPERBOT_PA_TOKEN }}
          branch: 'i18n-sync-learn'
          owner-repo: 'nhcarrigan/actions-testing'
          base: 'main'
          title: 'chore(i18n,learn): processed translations'
          body: 'This PR was opened auto-magically by Crowdin.'
          labels: 'crowdin-sync, scope: i18n, scope: learn'
          reviewers: 'nhcarrigan'
