name: 'Test NGINX config'
on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test_config:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout repo'
      uses: actions/checkout@v2
    - name: 'Test NGINX'
      run: 'sudo nginx -t -c nginx.conf -p `pwd`/'