name: No translate on GitHub
on:
  pull_request_target:
    branches:
      - "main"
    paths:
      - "curriculum/challenges/**"
      - "!curriculum/challenges/english/**"

jobs:
  has-translation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            // console.log(context.payload.pull_request.head);
            if (!context.payload.pull_request.head.fork) {
              await github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'This is not a fork - when this is true we should pass this workflow.'
            })
              return;
            } else {
              await github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'This IS a fork - when this is true we should FAIL this workflow.'
            })
              throw new Error("NA NA NA NA NA NA NA Can't touch this")
            }
