name: No translate on GitHub
on:
  pull_request_target:
    branches:
      - 'main'
    paths:
      - 'curriculum/challenges/**'
      - '!curriculum/challenges/english/**'

jobs:
  has-translation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            console.log("This is head");
            console.log(context.payload.pull_request.head);