name: CI - Node.js Test Current
env:
  NODE_OPTIONS: '--max_old_space_size=6144'

on:
  # Run on push events, but only for the below branches
  push:
    branches:
      - 'main'
      - 'prod-**'
  # Run on pull requests, but only for the below targets
  pull_request:
    branches:
      - 'main'
      - 'next-**'
  # Run on Merge Queue
  merge_group:
    types: [checks_requested]

permissions:
  contents: read

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [18.x]
      fail-fast: false

    steps:
      - uses: actions/github-script@98814c53be79b1d30f795b907e553d8679345975 # v6
        with:
          github-token: ${{ secrets.CAMPERBOT_NO_TRANSLATE }}
        script: |
          console.log('linted!')
      

  test:
    name: Test
    needs: lint
    runs-on: ubuntu-20.04

    strategy:
      fail-fast: false
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/github-script@98814c53be79b1d30f795b907e553d8679345975 # v6
        with:
          github-token: ${{ secrets.CAMPERBOT_NO_TRANSLATE }}
        script: |
          console.log('tested');

  test-upcoming:
    name: Test Upcoming Changes
    needs: lint
    runs-on: ubuntu-20.04

    strategy:
      fail-fast: false
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/github-script@98814c53be79b1d30f795b907e553d8679345975 # v6
        with:
          github-token: ${{ secrets.CAMPERBOT_NO_TRANSLATE }}
        script: |
          console.log('tested upcoming');

  test-localization:
    name: Localize
    needs: lint
    runs-on: ubuntu-20.04

    strategy:
      fail-fast: false
      matrix:
        node-version: [18.x]
        locale: [chinese, espanol]

    steps:
      - uses: actions/github-script@98814c53be79b1d30f795b907e553d8679345975 # v6
        with:
          github-token: ${{ secrets.CAMPERBOT_NO_TRANSLATE }}
        script: |
          console.log('tested localisation')

  failure-comment:
    name: Comment on i18n Failure
    needs: ['test', 'test-localization']
    runs-on: ubuntu-20.04
    if: ${{ needs.test.result == 'success' && needs.test-localization.result == 'failure' }}
    steps:
      - uses: actions/github-script@98814c53be79b1d30f795b907e553d8679345975 # v6
        with:
          github-token: ${{ secrets.CAMPERBOT_NO_TRANSLATE }}
        script: |
          const isDev = await github.rest.teams.getMembershipForUserInOrg({
            org: "freeCodeCamp",
            team_slug: "dev-team",
            username: context.payload.pull_request.user.login
          }).catch(() => ({status: 404}));
          if (context.payload.pull_request.user.login !== "camperbot" && isDev.status !== 200) {
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: "Hi,\n\nIt looks like the localization tests have failed. This is normal when there are significant curriculum changes in the English version.\n\nPlease check with the dev-team on [Discord]() or our [forums](https://forum.freecodecamp.org) if this means a Crowdin sync is required to address the scenario. They will confirm and take over helping you through the PR.\n\nThanks for your understanding and contribution."
            })
          } else if (isDev.status === 200) {
            core.setFailed('This PR appears to touch translated curriculum files, but since you are on the dev team there is no message.');
          }