name: "No changing translated files on GitHub"
on:
  pull_request_target:
    branches:
    - 'main'

jobs:
  has-translation:
    runs-on: ubuntu-latest
    steps:
    - name: Dump 
      env: 
      GITHUB_CONTEXT: ${{ toJSON(github)}}
      run: echo "$GITHUB_CONTEXT"
    - uses: actions/github-script@v3
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          await github.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: 'You appear to be translating files directly on GitHub. Please visit https://translate.freecodecamp.org instead.'
          })
          throw "You appear to be translating files directly on GitHub. Please visit https://translate.freecodecamp.org instead."
