name: Translate Chinese to Traditional
on:
  workflow_dispatch:
  schedule:
    # runs every day at 2 PM UTC
    - cron: "0 14 * * * "

jobs:
  translate-chinese:
    name: Translate
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout Source Files
        uses: actions/checkout@v2

      - name: Switch Branch
        run: git checkout -b translate-chinese

      - name: Install Dependencies
        working-directory: ./tools
        run: |
          cd ./crowdin
          npm ci

      - name: Generate Translations
        uses: ./tools/crowdin/actions/convert-chinese

      - name: Create Commit
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git add .
          git commit -m "feat(i18n): traditional chinese"
          git push origin translate-chinese -f

      - name: Generate PR
        uses: ./tools/crowdin/actions/pr-creator
        with:
          github-token: ${{ secrets.ACTIONS_CAMPERBOT_PA_TOKEN }}
          branch: "translate-chinese"
          owner-repo: "nhcarrigan/actions-testing"
          base: "main"
          title: "chore(i18n): translate chinese characters"
          body: "This PR was opened auto-magically."
          labels: ''
          reviewers: "nhcarrigan"
